export const MAKE_REQUEST = "MAKE_REQUEST";
export const REQUEST_RESOURCES_SUCCESS = "REQUEST_SUCCESS";
export const REQUEST_FAILURE = "REQUEST_FAILURE";
export const REQUEST_CURRENT_RESOURCE_SUCCESS = "REQUEST_CURRENT_RESOURCE_SUCCESS";
